### ISSUE TITLE
抽卡功能返回空白图片，有报错

### ISSUE THREAD

**Issue by deYangar** [SilveryStar/Adachi-BOT#106]
### 系统版本

Windows 10 专业工作站版 1909

### Node.js 版本

v13.13.0

### 应用版本

v2.2.0 3小时前最新版

### 启动方式

Forever

### 复述操作

重新clone，重新配置环境部署过，使用抽卡功能后返回空白图片，并且powershell有报错
使用其他功能时，例如uid信息、深渊信息，没发现问题
![QQ截图20211122002203](https://user-images.githubusercontent.com/70438628/142770389-b7523bcc-32d6-4f75-9e2a-e411ef05f102.jpg)

### 配置文件

```YAML
修改过commands.yml

silvery-star.wish:
  type: order
  auth: 1
  scope: 3
  headers:
    - ck
    - 十连
  enable: true
```

### 错误报告

```Text
(node:18680) UnhandledPromiseRejectionWarning: FetchError: request to https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/artifact/artifact.yml failed, reason: getaddrinfo ENOTFOUND adachi-bot.oss-cn-beijing.aliyuncs.com
    at ClientRequest.<anonymous> (C:\Green\Adachi-BOT\Adachi-BOT-master\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:18680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18680) UnhandledPromiseRejectionWarning: FetchError: request to https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/wish/config/character.json failed, reason: getaddrinfo ENOTFOUND adachi-bot.oss-cn-beijing.aliyuncs.com
    at ClientRequest.<anonymous> (C:\Green\Adachi-BOT\Adachi-BOT-master\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:18680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18680) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'upFourStar' of undefined
    at Wish.<anonymous> (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\wish.ts:159:52)
    at step (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\wish.ts:44:23)
    at Object.next (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\wish.ts:25:53)
    at fulfilled (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\wish.ts:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:18680) UnhandledPromiseRejectionWarning: FetchError: request to https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/wish/config/weapon.json failed, reason: getaddrinfo ENOTFOUND adachi-bot.oss-cn-beijing.aliyuncs.com
    at ClientRequest.<anonymous> (C:\Green\Adachi-BOT\Adachi-BOT-master\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:18680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:18680) UnhandledPromiseRejectionWarning: FetchError: request to https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/alias/alias.yml failed, reason: getaddrinfo ENOTFOUND adachi-bot.oss-cn-beijing.aliyuncs.com
    at ClientRequest.<anonymous> (C:\Green\Adachi-BOT\Adachi-BOT-master\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:18680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

**Comment by deYangar** [comment]
傻了，原来是开着系统代理，关掉就好了
