### ISSUE TITLE
Type 'unknown' is not assignable to type 'OrderMatchResult | Unmatch'.

### ISSUE THREAD

**Issue by Archergh** [SilveryStar/Adachi-BOT#117]
### 系统版本

linux

### Node.js 版本

v14.15.4

### 应用版本

2.2.0-bugfix3

### 复述操作

 npm start

### 配置文件

```YAML
number: 11
password: 11
master: 11
header: ""
platform: 1
dbPort: 6379
webConsole:
  enable: true
  consolePort: 80
  tcpLoggerPort: 54921
  jwtSecret: "ffffffff"
```

### 错误报告

```Text
/tools/bot/yuan/Adachi-BOT-master/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ? Unable to compile TypeScript:
src/modules/command/order.ts:80:3 - error TS2322: Type 'unknown' is not assignable to type 'OrderMatchResult | Unmatch'.
  Type 'unknown' is not assignable to type 'Unmatch'.

80   return  data;
     ~~~~~~~~~~~~~

    at createTSError (/tools/bot/yuan/Adachi-BOT-master/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/tools/bot/yuan/Adachi-BOT-master/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/tools/bot/yuan/Adachi-BOT-master/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/tools/bot/yuan/Adachi-BOT-master/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/tools/bot/yuan/Adachi-BOT-master/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/tools/bot/yuan/Adachi-BOT-master/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adachi-bot@2.2.0-bugfix3 start: `ts-node -r tsconfig-paths/register app.ts --files`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the adachi-bot@2.2.0-bugfix3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-25T08_19_01_217Z-debug.log
```

**Comment by SilveryStar** [comment]
你这是从什么版本更新上来的……建议重新clone一份

**Comment by Archergh** [comment]
[root@iZ1ncbfsvwjaztZ Adachi-BOT]# npm start

> adachi-bot@2.2.0-bugfix3 start /tools/bot/yuan/Adachi-BOT
> ts-node -r tsconfig-paths/register app.ts --files







请问一下：这是什么原因，一点反应没有？

**Comment by SilveryStar** [comment]
https://docs.adachi.top/faq/#%E6%9B%B4%E6%96%B0%E8%87%B3-v2-2-0-%E5%90%8E-%E6%8E%A7%E5%88%B6%E5%8F%B0%E6%97%A0%E8%BE%93%E5%87%BA

**Comment by Archergh** [comment]
{"category":"[Android:2844026145]","level":"INFO","color":"green","message":"Redis 数据库已连接","time":"15:47:00.880"}
{"category":"[Android:2844026145]","level":"ERROR","color":"red","message":"插件加载异常: Error: Failed to launch the browser process!\n/tools/bot/yuan/Adachi-BOT/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n","time":"15:47:00.887"}
