### ISSUE TITLE
今日黄历，不回复，有报错

### ISSUE THREAD

**Issue by deYangar** [SilveryStar/Adachi-BOT#118]
### 系统版本

Windows 10 专业版 21H1

### Node.js 版本

v13.13.0

### 应用版本

v2.2.0-bugfix3

### 启动方式

Forever

### 复述操作

发送“今日黄历”，浏览器里的那个日志有报错，然后没回复，powershell里面没报错

### 配置文件

```YAML
修改过commands.yml

silvery-star.almanac:
  type: order
  auth: 1
  scope: 3
  headers:
    - 今日黄历
  enable: true
```

### 错误报告

```Text
[01:19:03.920] [Android:1563077598] [ERROR] - RangeError: Maximum call stack size exceeded
    at Function.AlmanacClass.getDailyNumber (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\almanac.ts:44:19)
    at AlmanacClass.getUnits (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\almanac.ts:64:34)
    at AlmanacClass.getUnits (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\almanac.ts:72:10)
    at AlmanacClass.getUnits (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\almanac.ts:72:10)
    at AlmanacClass.getUnits (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\almanac.ts:72:10)
    at AlmanacClass.getUnits (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\almanac.ts:72:10)
    at AlmanacClass.getUnits (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\almanac.ts:72:10)
    at AlmanacClass.getUnits (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\almanac.ts:72:10)
    at AlmanacClass.getUnits (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\almanac.ts:72:10)
    at AlmanacClass.getUnits (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\almanac.ts:72:10)
```

**Comment by deYangar** [comment]
尝试过重新完整clone，commands.yml配置不修改，也会报错

**Comment by SilveryStar** [comment]
其实以前也出过这个问题，貌似和平台和时间有关，不过不清楚怎么修，还得研究研究

**Comment by deYangar** [comment]
> 其实以前也出过这个问题，貌似和平台和时间有关，不过不清楚怎么修，还得研究研究

嗷，这个出现确实没啥规律。从发issues到现在电脑一直开着没动过，然后前几分钟又突然能发黄历了

**Comment by SilveryStar** [comment]
希望修好了（捂脸
