### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by tendapc** [SilveryStar/Adachi-BOT#119]
### 系统版本

win10

### Node.js 版本

v17.0.1

### 应用版本

2.2.0-bugfix3

### 启动方式

Forever

### 复述操作

部署完成后，config中无配置文件，npm run login可以正常登陆接受消息，npm run start 报错如下

### 错误报告

```Text
Administrator@10_0_8_10 MINGW64 ~/Desktop/Adachi-BOT1/Adachi-BOT (master)
$ npm run start

> adachi-bot@2.2.0-bugfix3 start
> ts-node -r tsconfig-paths/register app.ts --files


C:\Users\Administrator\Desktop\Adachi-BOT1\Adachi-BOT\node_modules\express-jwt\lib\index.js:20
  if (!options || !options.secret) throw new Error('secret should be set');
                                         ^
Error: secret should be set
    at Object.module.exports [as default] (C:\Users\Administrator\Desktop\Adachi-BOT1\Adachi-BOT\node_modules\express-jwt\lib\index.js:20:42)
    at Function.WebConsole.JWT (C:\Users\Administrator\Desktop\Adachi-BOT1\Adachi-BOT\src\web-console\backend\index.ts:83:13)
    at WebConsole.useApi (C:\Users\Administrator\Desktop\Adachi-BOT1\Adachi-BOT\src\web-console\backend\index.ts:100:35)
    at WebConsole.createConsole (C:\Users\Administrator\Desktop\Adachi-BOT1\Adachi-BOT\src\web-console\backend\index.ts:37:8)
    at new WebConsole (C:\Users\Administrator\Desktop\Adachi-BOT1\Adachi-BOT\src\web-console\backend\index.ts:26:8)
    at new Adachi (C:\Users\Administrator\Desktop\Adachi-BOT1\Adachi-BOT\src\modules\bot.ts:55:4)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\Adachi-BOT1\Adachi-BOT\app.ts:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Module.m._compile (C:\Users\Administrator\Desktop\Adachi-BOT1\Adachi-BOT\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
```

**Comment by SilveryStar** [comment]
setting.yml -> webConsole => jwtSecret 没设置吧

**Comment by tendapc** [comment]
谢谢，大佬，解决了
