### ISSUE TITLE
运行出错 机器人刷屏

### ISSUE THREAD

**Issue by Annabel0530** [SilveryStar/Adachi-BOT#130]
### 系统版本

Windows 10 (19042.1348)

### Node.js 版本

v12.18.1

### 应用版本

2.2.2

### 复述操作

未进行任何操作，突发，日志里出现出错报告后开始只给两个用户刷屏发送树脂数量
![image](https://user-images.githubusercontent.com/40524485/144733500-5d799a79-938b-418e-909b-28619b80fc19.png)

### 配置文件

```YAML
未修改
```

### 错误报告

```Text
Error: getaddrinfo ENOTFOUND api-takumi.mihoyo.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api-takumi.mihoyo.com'
}
Error: getaddrinfo ENOTFOUND api-takumi.mihoyo.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api-takumi.mihoyo.com'
}
```

**Comment by SilveryStar** [comment]
你这是不是断过网啊，我笔记本运行的时候如果合上过再打开也会这个样子

**Comment by Annabel0530** [comment]
> 你这是不是断过网啊，我笔记本运行的时候如果合上过再打开也会这个样子

😂我也不是很清楚，发生的时候有几个小时没人用BOT，我开手机就发现已经给我刷99+了

**Comment by SilveryStar** [comment]
emmm，目前判断应该还是网络问题，但是要改的话不知道怎么下手，这个 issue 先放着

**Comment by Cn7ci4** [comment]
断网回来之后会错误发送这个树脂提示,但一般只会发一遍最多两遍,这种一直刷屏没遇到过

**Comment by mashirozx** [comment]
![-4f8c5dcfe894dc47](https://user-images.githubusercontent.com/16148054/145720627-319633d2-cfe8-41a2-a9b7-881aa0865c07.png)
这边同样啊。。

**Comment by deYangar** [comment]
昨晚我也遇到了，发生的时候，网络质量很差

**bot版本**
2.2.4-optimize3

**错误报告**
[00:00:21.155] [iPad:1563077598] [ERROR] - FetchError: request to https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/wish/config/weapon.json failed, reason: connect ETIMEDOUT 59.110.185.152:443
    at ClientRequest.<anonymous> (C:\Green\Adachi-BOT\Adachi-BOT-master\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

[00:00:21.156] [iPad:1563077598] [ERROR] - FetchError: request to https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/daily/daily.yml failed, reason: connect ETIMEDOUT 59.110.185.152:443
    at ClientRequest.<anonymous> (C:\Green\Adachi-BOT\Adachi-BOT-master\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

[00:00:21.156] [iPad:1563077598] [ERROR] - FetchError: request to https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/character/id.yml failed, reason: connect ETIMEDOUT 59.110.185.152:443
    at ClientRequest.<anonymous> (C:\Green\Adachi-BOT\Adachi-BOT-master\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

[00:00:21.157] [iPad:1563077598] [ERROR] - FetchError: request to https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/alias/alias.yml failed, reason: connect ETIMEDOUT 59.110.185.152:443
    at ClientRequest.<anonymous> (C:\Green\Adachi-BOT\Adachi-BOT-master\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

[00:00:21.341] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAAChSPTJkzYbduFQE=]

[00:01:00.271] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAAChvN4e3iYbduPAE=]

[00:01:00.391] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAAChz9nIF4YbduPAE=]

[00:02:00.262] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAACiJVlWszYbdueAE=]

[00:02:00.368] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAACiNCyNrrYbdueAE=]

[00:03:00.232] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAACilKey/TYbdutAE=]

[00:03:00.342] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAACir8Q4GXYbdutAE=]

[00:04:00.302] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAACjL2mQCOYbdu8AE=]

[00:04:00.392] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAACjPH3+ZmYbdu8AE=]

[00:05:00.272] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAACjkDSK2wYbdvLAE=]

[00:05:00.372] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAACjrVMc8uYbdvLAE=]

[00:06:00.263] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAACkAQGXZCYbdvaAE=]

[00:06:00.372] [iPad:1563077598] [INFO] - send to: [Private: 1069064815 / message_id: P7iibwAACkEjittDYbdvaAE=]

**当时截图**
每分钟发两条
![QQ截图20211214115439](https://user-images.githubusercontent.com/70438628/145930300-8fe7b1c4-ed77-465c-80c0-13b8460c5178.jpg)

**Comment by King-Nameless** [comment]
我也出现了，今天一直在提示

**Comment by SilveryStar** [comment]
> 我也出现了，今天一直在提示

今天应该是api的问题，频道里统一都炸了，重启一下就行，目前有一点修复思路了，晚点修

**Comment by King-Nameless** [comment]
> > 我也出现了，今天一直在提示
> 
> 今天应该是api的问题，频道里统一都炸了，重启一下就行，目前有一点修复思路了，晚点修

重启没用啊，还是一直在私聊提醒，我给他关了，坐等大佬修复_(:зゝ∠)_
