### ISSUE TITLE
启动无关紧要的报错&BOT邀请权限设定问题

### ISSUE THREAD

**Issue by Accelerator1213** [SilveryStar/Adachi-BOT#133]
### 系统版本

centos_8_0_x64

### Node.js 版本

13.13.0

### 应用版本

2.2.2

### 启动方式

Docker

### 复述操作

npm start启动后，BOT正常运行，Web Console也能正常访问，但是会出现一个错误提示（但是没有任何影响）。

&

我把BOT的邀请权限修改为user，但是master邀请BOT加群却提示没有权限。

（这个不能调user吗）

### 配置文件

```YAML
inviteAuth: user
```

### 错误报告

```Text
[root@Genshin Adachi-BOT]# npm start

> adachi-bot@2.2.2 start /root/Adachi-BOT
> ts-node -r tsconfig-paths/register app.ts --files

Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Function.serverListen [as listen] (/root/Adachi-BOT/node_modules/express-ws/lib/index.js:42:40)
    at Server.<anonymous> (/root/Adachi-BOT/src/web-console/backend/index.ts:64:13)
    at Server.emit (events.js:315:20)
    at Server.EventEmitter.emit (domain.js:485:12)
    at TCP.onconnection (net.js:1556:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adachi-bot@2.2.2 start: `ts-node -r tsconfig-paths/register app.ts --files`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the adachi-bot@2.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-07T10_35_57_378Z-debug.log
```

**Comment by Accelerator1213** [comment]
![image](https://user-images.githubusercontent.com/82789349/145014063-afad96f3-8c7c-468d-b094-ac2244e1929f.png)

补个图。

**Comment by SilveryStar** [comment]
1. 报错那个不影响正常使用，报错的位置是 web console，因为 80 端口占用了。这个 `npm start` 是不生效的，估计是你哪里已经启动了一个应用才能正常用
2. 邀请权限[文档](https://docs.adachi.top/config/#inviteauth)里写了是没支持 `user`。不过现在那个部分有点问题，你改成 `master` 应该也邀请不了，下个版本会修
