### ISSUE TITLE
升级最新版本报错 Error: Cannot find module 'whatwg-url'

### ISSUE THREAD

**Issue by NiHang** [SilveryStar/Adachi-BOT#139]
### 系统版本

macOS 11.4

### Node.js 版本

v15.14.0

### 应用版本

2.2.3-bugfix2

### 启动方式

Docker

### 复述操作

拉取最新代码，重新启动报错

### 错误报告

```Text
{"category":"[MacOS:3627220093]","level":"MARK","color":"grey","message":"----------","time":"13:48:01.658"}
{"category":"[MacOS:3627220093]","level":"MARK","color":"grey","message":"Package Version: oicq@1.21.2 (Released on 2021/10/10)","time":"13:48:01.664"}
{"category":"[MacOS:3627220093]","level":"MARK","color":"grey","message":"View Changelogs：https://github.com/takayama-lily/oicq/releases","time":"13:48:01.664"}
{"category":"[MacOS:3627220093]","level":"MARK","color":"grey","message":"----------","time":"13:48:01.665"}
{"category":"[MacOS:3627220093]","level":"MARK","color":"grey","message":"正在探索可用服务器...","time":"13:48:01.696"}
{"category":"[MacOS:3627220093]","level":"INFO","color":"green","message":"插件 @help 加载完成","time":"13:48:02.393"}
{"category":"[MacOS:3627220093]","level":"INFO","color":"green","message":"插件 @management 加载完成","time":"13:48:03.216"}
{"category":"[MacOS:3627220093]","level":"ERROR","color":"red","message":"Error: Cannot find module 'whatwg-url'\nRequire stack:\n- /bot/node_modules/node-fetch/lib/index.js\n- /bot/src/plugins/genshin/utils/api.ts\n- /bot/src/plugins/genshin/module/artifact.ts\n- /bot/src/plugins/genshin/module/index.ts\n- /bot/src/plugins/genshin/init.ts\n- /bot/src/modules/plugin.ts\n- /bot/src/modules/bot.ts\n- /bot/app.ts\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)\n    at Function.Module._resolveFilename (/bot/node_modules/tsconfig-paths/lib/register.js:75:40)\n    at Function.Module._load (internal/modules/cjs/loader.js:667:27)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/bot/node_modules/node-fetch/lib/index.js:10:33)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)","time":"13:48:05.321"}
```

**Comment by isad-name** [comment]
试试重新运行npm install 看上去像是少依赖

**Comment by NiHang** [comment]
> 试试重新运行npm install 看上去像是少依赖

是缺少了依赖。我用docker exec -it adachi-bot /bin/bash 进到docker里用npm install更新了依赖可以了。
但是我有个问题npm install yaml oicq 这个命令不会更新docker里面的依赖包吗？每次有增加依赖都需要到docker里收到更新吗？

**Comment by isad-name** [comment]
大佬给的docker的更新方式
docker-compose stop
docker rm adachi-bot
docker rmi adachi-bot:2.2.0
docker-compose up -d
我之前自己试的时候是把docker里这个2.2.0的容器连带镜像都删了，数据库服务器的没删，然后用compose up重新运行
再进入docker命令行里更新了一下chrome那个内核就可以用了

**Comment by NiHang** [comment]
谢谢，那就是我更新的操作有问题，用这种卸载容器再卸载镜像的方式应该是可以的。

**Comment by SilveryStar** [comment]
> 但是我有个问题npm install yaml oicq 这个命令不会更新docker里面的依赖包吗？

这个当然是不会的

> 每次有增加依赖都需要到docker里手动更新吗？

最新的 dockerfile 已经把逻辑改成每次启动都会尝试运行 cnpm install 安装依赖，所以以后应该不会再这类问题

**Comment by isad-name** [comment]
正好就这这个issue问一下
{"category":"[iPad:229]","level":"ERROR","color":"red","message":"插件加载异常: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (884014).","time":"18:18:31.401"}
windows的docker里每次重新部署都会提示这个，用命令行进去npm i才能解决，这是什么高级bug

**Comment by SilveryStar** [comment]
> windows的docker里每次重新部署都会提示这个，用命令行进去npm i才能解决，这是什么高级bug

这就是单纯的东西没下载下来，之后想办法解决一下

**Comment by NiHang** [comment]
好的，谢谢解答！
