### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript

### ISSUE THREAD

**Issue by mashirozx** [SilveryStar/Adachi-BOT#145]
### Node.js 版本

16

### 应用版本

2.2.5-bugfix1

### 启动方式

Docker

### 错误报告

```Text
[2021-12-17T12:34:29.276] [ERROR] [Android:33xxx4279] - TSError: ⨯ Unable to compile TypeScript:

src/modules/renderer.ts(137,24): error TS2571: Object is of type 'unknown'.

src/modules/renderer.ts(152,24): error TS2571: Object is of type 'unknown'.


    at createTSError (/bot/node_modules/ts-node/src/index.ts:513:12)

    at reportTSError (/bot/node_modules/ts-node/src/index.ts:517:19)

    at getOutput (/bot/node_modules/ts-node/src/index.ts:752:36)

    at Object.compile (/bot/node_modules/ts-node/src/index.ts:968:32)

    at Module.m._compile (/bot/node_modules/ts-node/src/index.ts:1056:42)

    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Object.require.extensions.<computed> [as .ts] (/bot/node_modules/ts-node/src/index.ts:1059:12)

    at Module.load (internal/modules/cjs/loader.js:863:32)

    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

    at Module.require (internal/modules/cjs/loader.js:887:19)
```

### Info
未启用Web UI

QQ初始化完毕，也能收到消息，但是对消息无响应，没有看见报错。

**Comment by mashirozx** [comment]
回滚到2.2.4一切正常
