### ISSUE TITLE
今日素材功能出现问题，控制台有报错

### ISSUE THREAD

**Issue by deYangar** [SilveryStar/Adachi-BOT#149]
### 系统版本

Windows 10 专业版 21H1

### Node.js 版本

v13.13.0

### 应用版本

2.2.5-bugfix2

### 启动方式

Forever

### 复述操作

一直挂着，没做啥操作，18号还是20号早上开始不会自动发送，然后试着手动发送，发现有报错。出问题前一天都能用，没改啥东西。
![QQ截图20211221115727](https://user-images.githubusercontent.com/70438628/146868543-223a4738-ef5e-4e68-b106-8d541fb27582.jpg)

### 配置文件

```YAML
commands.yml

silvery-star.today:
  type: order
  auth: 1
  scope: 3
  headers:
    - 今日素材
  enable: true
```

### 错误报告

```Text
[11:50:51.744] [iPad:1563077598] [ERROR] - TypeError: Cannot read property 'newPage' of undefined
    at Object.<anonymous> (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\utils\render.ts:38:45)
    at step (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\utils\render.ts:33:23)
    at Object.next (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\utils\render.ts:14:53)
    at C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\utils\render.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\utils\render.ts:4:12)
    at Object.render (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\utils\render.ts:82:12)
    at DailyClass.<anonymous> (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\daily.ts:180:16)
    at step (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\daily.ts:33:23)
    at Object.next (C:\Green\Adachi-BOT\Adachi-BOT-master\src\plugins\genshin\module\daily.ts:14:53)
```

**Comment by deYangar** [comment]
试过重启机器人，不行
然后用源压缩包里的render.ts和daily.ts替换现在有的两个文件也不行

**Comment by deYangar** [comment]
更新bugfix3版本后，重启过电脑，暂时还是报同样错误
![QQ截图20211222013852](https://user-images.githubusercontent.com/70438628/146974358-d7de443f-86d6-4879-a208-242ad8f2a26a.jpg)

**Comment by SilveryStar** [comment]
我突然意识到这可能是你代码没拉对，`v2.2.5` 已经没有 `render.ts` 这个文件了

**Comment by deYangar** [comment]
> 我突然意识到这可能是你代码没拉对，`v2.2.5` 已经没有 `render.ts` 这个文件了

啊这 绝了，不过用bugfix4之后又好了，今日素材能用了
