### ISSUE TITLE
绑定私人服务失败

### ISSUE THREAD

**Issue by AzusaYukina** [SilveryStar/Adachi-BOT#153]
### 系统版本

Windows 10 Pro (19043.1348)

### Node.js 版本

12.22.7

### 应用版本

2.2.5-bugfix4

### 复述操作

由于此前出现 #130 中所提及问题，因此重新全新部署了 bot
启动后，使用 `/ps` 绑定私人服务，输入 `/confirm [cookie]` 后控制台有错误提示，聊天窗口无回复

### 配置文件

```YAML
未修改
```

### 错误报告

```Text
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at D:\Rina\Desktop\bot\GanYu\Genshin\Adachi-BOT\src\plugins\genshin\utils\api.ts:58:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by SilveryStar** [comment]
跟米游社接口有关的一切功能暂时都是不可用的

**Comment by SilveryStar** [comment]
#154
