### ISSUE TITLE
云服务器部署后运行出现'浏览器启动失败'错误

### ISSUE THREAD

**Issue by RDThird** [SilveryStar/Adachi-BOT#158]
### 系统版本

CentOS 7.9

### Node.js 版本

v14.18.1

### 应用版本

2.2.5-update5

### 启动方式

Forever

### 复述操作

- 本地运行时均可正常使用，但部署到云服务器后启动出现`浏览器启动失败`的提示
- 除生成图片相关以外的功能可正常使用
- 在调用到需要生成图片的指令时回执`图片渲染异常，请联系持有者进行反馈`，后台提示`浏览器未启动`
- 运行期间含`探索服务器失败`的warning，未知是否产生影响

### 配置文件

```YAML
qrcode: false
number: 123456
password: 123456
master: 123456
header: "#"
platform: 4
atUser: true
inviteAuth: master
countThreshold: 60
groupIntervalTime: 1500
privateIntervalTime: 2000
helpMessageStyle: message
logLevel: info
dbPort: 6379
webConsole:
  enable: true
  consolePort: 9999
  tcpLoggerPort: 25566
  jwtSecret: 123456
atBOT: false
```

### 错误报告

```Text
# 本地运行成功
[10:41:23.599] [MacOS:604***740] [MARK] [Event] ----------
[10:41:23.600] [MacOS:604***740] [MARK] [Event] Package Version: oicq@1.21.3 (Released on 2021/12/08)
[10:41:23.600] [MacOS:604***740] [MARK] [Event] View Changelogs：https://github.com/takayama-lily/oicq/releases
[10:41:23.601] [MacOS:604***740] [MARK] [Event] ----------
[10:41:23.612] [MacOS:604***740] [MARK] [Event] 正在探索可用服务器...
[10:41:23.958] [MacOS:604***740] [INFO] [Event] 插件 @help 加载完成
[10:41:24.302] [MacOS:604***740] [INFO] [Event] 插件 @management 加载完成
[10:41:27.300] [MacOS:604***740] [INFO] [Event] 插件 genshin 加载完成
[10:41:27.404] [MacOS:604***740] [INFO] [Event] 插件 tools 加载完成
[10:41:27.405] [MacOS:604***740] [INFO] [Event] 事件监听启动成功
[10:41:27.405] [MacOS:604***740] [INFO] [Event] Express 服务器已启动
[10:41:27.443] [MacOS:604***740] [INFO] [Event] Redis 数据库已连接
[10:41:27.816] [MacOS:604***740] [INFO] [Event] 浏览器启动成功
[10:41:27.836] [MacOS:604***740] [MARK] [Event] connecting to 109.244.128.213:8080
[10:41:27.881] [MacOS:604***740] [MARK] [Event] 109.244.128.213:8080 connected
[10:41:28.115] [MacOS:604***740] [INFO] [Event] 用户 101***723 的实时便笺数据查询成功
[10:41:28.164] [MacOS:604***740] [MARK] [Event] Welcome, Paimon ! 初始化资源...
[10:41:28.572] [MacOS:604***740] [MARK] [Event] 加载了116个好友，16个群，9个陌生人。
[10:41:28.640] [MacOS:604***740] [MARK] [Event] 初始化完毕，开始处理消息。

# 云服启动阶段报错
[10:22:47.119] [MacOS:604***740] [ERROR] - Invoke failed, because -> client is not online
[10:22:47.120] [MacOS:604***740] [ERROR] - 浏览器启动失败: Error: Failed to launch the browser process!
/home/Adachi-BOT/node_modules/puppeteer/.local-chromium/linux-884014/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at onClose (/home/Adachi-BOT/node_modules/puppeteer/src/node/BrowserRunner.ts:220:9)
    at Interface.<anonymous> (/home/Adachi-BOT/node_modules/puppeteer/src/node/BrowserRunner.ts:206:50)
    at Interface.emit (events.js:412:35)
    at Interface.emit (domain.js:475:12)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

# 云服调用阶段报错
[09:35:49.854] [MacOS:604***740] [ERROR] - Error: 浏览器未启动
    at Renderer.<anonymous> (/www/wwwroot/rds-bot.delamer.ltd/Adachi-BOT/src/modules/renderer.ts:97:10)
    at step (/www/wwwroot/rds-bot.delamer.ltd/Adachi-BOT/src/modules/renderer.ts:33:23)
    at Object.next (/www/wwwroot/rds-bot.delamer.ltd/Adachi-BOT/src/modules/renderer.ts:14:53)
    at /www/wwwroot/rds-bot.delamer.ltd/Adachi-BOT/src/modules/renderer.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/www/wwwroot/rds-bot.delamer.ltd/Adachi-BOT/src/modules/renderer.ts:4:12)
    at Renderer.render (/www/wwwroot/rds-bot.delamer.ltd/Adachi-BOT/src/modules/renderer.ts:145:16)
    at Renderer.<anonymous> (/www/wwwroot/rds-bot.delamer.ltd/Adachi-BOT/src/modules/renderer.ts:149:38)
    at step (/www/wwwroot/rds-bot.delamer.ltd/Adachi-BOT/src/modules/renderer.ts:33:23)
    at Object.next (/www/wwwroot/rds-bot.delamer.ltd/Adachi-BOT/src/modules/renderer.ts:14:53)

# 其他警告
[09:14:16.880] [MacOS:604***740] [MARK] - 正在探索可用服务器...
[09:14:17.412] [MacOS:604***740] [INFO] - 插件 @help 加载完成
[09:14:18.224] [MacOS:604***740] [INFO] - 插件 @management 加载完成
[09:14:25.179] [MacOS:604***740] [INFO] - 插件 genshin 加载完成
[09:14:25.599] [MacOS:604***740] [INFO] - 插件 tools 加载完成
[09:14:25.601] [MacOS:604***740] [INFO] - 事件监听启动成功
[09:14:25.602] [MacOS:604***740] [INFO] - Express 服务器已启动
[09:19:30.422] [MacOS:604***740] [WARN] - 探索服务器失败: timeout
```

**Comment by SilveryStar** [comment]
缺少依赖
```
yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc
```

**Comment by RDThird** [comment]
安装依赖后解决问题，感激不尽
附：探索服务器失败的警告依然存在，但目前使用到的功能均可正常运作，暂未发现有何影响
