### ISSUE TITLE
[10:59:52.909] [Android:161009029] [ERROR] - Error: 浏览器未启动

### ISSUE THREAD

**Issue by liuqianpan2008** [SilveryStar/Adachi-BOT#165]
### 系统版本

CentOS Linux release 8.4.2105

### Node.js 版本

v17.3.1

### 应用版本

Update to v2.2.7

### 启动方式

Docker

### 复述操作

![K$VQ9UPQXHV6B WB%Q3Z AF](https://user-images.githubusercontent.com/80571808/149140984-4a3d15a9-f6d0-4246-bc03-bd853ec1c757.png)

[12:31:55.108] [Android:*****] [INFO] [Recv] [Group] #note
[12:31:55.498] [Android:*****] [INFO] [Event] 用户 100747598 的实时便笺数据查询成功
[12:31:55.499] [Android:*****] [ERROR] [Event] Error: 浏览器未启动
    at Renderer.<anonymous> (/data/Adachi-BOT/src/modules/renderer.ts:97:10)
    at step (/data/Adachi-BOT/src/modules/renderer.ts:33:23)
    at Object.next (/data/Adachi-BOT/src/modules/renderer.ts:14:53)
    at /data/Adachi-BOT/src/modules/renderer.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/data/Adachi-BOT/src/modules/renderer.ts:4:12)
    at Renderer.render (/data/Adachi-BOT/src/modules/renderer.ts:145:16)
    at Renderer.<anonymous> (/data/Adachi-BOT/src/modules/renderer.ts:149:38)
    at step (/data/Adachi-BOT/src/modules/renderer.ts:33:23)
    at Object.next (/data/Adachi-BOT/src/modules/renderer.ts:14:53)

### 配置文件

```YAML
全部为默认配置，未做修改
```

### 错误报告

```Text
[10:59:52.909] [Android:161009029] [ERROR] - Error: 浏览器未启动
    at Renderer.<anonymous> (/data/Adachi-BOT/src/modules/renderer.ts:97:10)
    at step (/data/Adachi-BOT/src/modules/renderer.ts:33:23)
    at Object.next (/data/Adachi-BOT/src/modules/renderer.ts:14:53)
    at /data/Adachi-BOT/src/modules/renderer.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/data/Adachi-BOT/src/modules/renderer.ts:4:12)
    at Renderer.render (/data/Adachi-BOT/src/modules/renderer.ts:145:16)
    at Renderer.<anonymous> (/data/Adachi-BOT/src/modules/renderer.ts:149:38)
    at step (/data/Adachi-BOT/src/modules/renderer.ts:33:23)
    at Object.next (/data/Adachi-BOT/src/modules/renderer.ts:14:53)
```

**Comment by SilveryStar** [comment]
这种情况是bot运行一段时间后才出现的吗，之前是否能正常运行

**Comment by liuqianpan2008** [comment]
已解决，根据 https://github.com/SilveryStar/Adachi-BOT/issues/158 解决了
