### ISSUE TITLE
机器人报错：图片渲染异常，请联系持有者进行反馈

### ISSUE THREAD

**Issue by mashirozx** [SilveryStar/Adachi-BOT#169]
### 复述操作

![image](https://user-images.githubusercontent.com/16148054/150761554-bd079563-49df-462e-b02f-15da547dedbc.png)

### 错误报告

```Text
[2022-01-24T17:57:17.124] [ERROR] [Android:3443939253] - Error: Node has 0 height.

    at Object.assert (/bot/node_modules/puppeteer/src/common/assert.ts:23:21)

    at ElementHandle.screenshot (/bot/node_modules/puppeteer/src/common/JSHandle.ts:843:5)

    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by mashirozx** [comment]
最新版代码

**Comment by SilveryStar** [comment]
这个就是单纯因为各种可能的问题没获取到完整的数据导致渲染失败了，我没办法解决（
