### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by tendapc** [SilveryStar/Adachi-BOT#170]
### 系统版本

win10

### Node.js 版本

v17.0.1

### 应用版本

2.2.8-bugfix3

### 启动方式

Docker

### 复述操作

本来正常使用，重启报错，无响应

### 配置文件

```YAML
无改动
```

### 错误报告

```Text
[2022-01-26T00:55:20.093] [ERROR] - TSError: ⨯ Unable to compile TypeScript:
src/modules/renderer.ts(105,53): error TS2345: Argument of type '{ encoding: string; }' is not assignable to parameter of type 'ScreenshotOptions'.
  Types of property 'encoding' are incompatible.
    Type 'string' is not assignable to type '"base64" | "binary" | undefined'.

    at createTSError (D:\Adachi-BOT\node_modules\ts-node\src\index.ts:513:12)
    at reportTSError (D:\Adachi-BOT\node_modules\ts-node\src\index.ts:517:19)
    at getOutput (D:\Adachi-BOT\node_modules\ts-node\src\index.ts:752:36)
    at Object.compile (D:\Adachi-BOT\node_modules\ts-node\src\index.ts:968:32)
    at Module.m._compile (D:\Adachi-BOT\node_modules\ts-node\src\index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Adachi-BOT\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
```

**Comment by SilveryStar** [comment]
这是什么突发恶疾…… 你检查一下 `/src/modules/renderer.ts L103` 和下面一不一样，如何重启一下设备试试吧
https://github.com/SilveryStar/Adachi-BOT/blob/91c79a660353512a7bcb8c4f796e79e15e205a92/src/modules/renderer.ts#L103

**Comment by tendapc** [comment]
![image](https://user-images.githubusercontent.com/69566610/151156976-d22d513d-6ced-4e24-980b-d7d28c7bbf28.png)

**Comment by tendapc** [comment]
重启似乎并不能解决

**Comment by SilveryStar** [comment]
你再更新试试
