### ISSUE TITLE
八重神子.json空白  导致今日素材错误

### ISSUE THREAD

**Issue by wickedll** [SilveryStar/Adachi-BOT#180]
### 错误报告

```Text
FetchError: Invalid response body while trying to fetch https://adachi-bot.oss-cn-beijing.aliyuncs.com/Version2/info/docs/%E5%85%AB%E9%87%8D%E7%A5%9E%E5%AD%90.json: incorrect header check
    at Gunzip.<anonymous> (/home/nodePro/Adachi-BOT/node_modules/_node-fetch@2.6.7@node-fetch/lib/index.js:400:12)
    at Gunzip.emit (events.js:327:22)
    at Gunzip.EventEmitter.emit (domain.js:485:12)
    at Zlib.zlibOnError [as onerror] (zlib.js:183:8)
```

**Comment by SilveryStar** [comment]
估计是 oss 那边抽筋了，现在修好了，不过今天有问题的数据不会主动刷新，需要重启bot或者等明天
