### ISSUE TITLE
进行uid查询时报错SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by weitanai123** [SilveryStar/Adachi-BOT#194]
### 系统版本

centos 7.6

### Node.js 版本

16.14.0

### 应用版本

2.2.10-bugfix1

### 启动方式

Docker

### 复述操作

启动信息应该一切正常，以下是启动信息
[root@VM-16-16-centos Adachi-BOT]# docker-compose up 
[+] Running 2/0
 ⠿ Container adachi-redis  Created                                                             0.0s
 ⠿ Container adachi-bot    Created                                                             0.0s
Attaching to adachi-bot, adachi-redis
adachi-redis  | 1:C 07 Mar 2022 10:08:27.484 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
adachi-redis  | 1:C 07 Mar 2022 10:08:27.484 # Redis version=6.2.3, bits=64, commit=00000000, modified=0, pid=1, just started
adachi-redis  | 1:C 07 Mar 2022 10:08:27.484 # Configuration loaded
adachi-redis  | 1:M 07 Mar 2022 10:08:27.485 * monotonic clock: POSIX clock_gettime
adachi-redis  | 1:M 07 Mar 2022 10:08:27.485 * Running mode=standalone, port=56379.
adachi-redis  | 1:M 07 Mar 2022 10:08:27.485 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
adachi-redis  | 1:M 07 Mar 2022 10:08:27.485 # Server initialized
adachi-redis  | 1:M 07 Mar 2022 10:08:27.486 * DB loaded from append only file: 0.001 seconds
adachi-redis  | 1:M 07 Mar 2022 10:08:27.486 * Ready to accept connections
adachi-bot    | ✔ Installed 38 packages
adachi-bot    | ✔ Linked 0 latest versions
adachi-bot    | ✔ Run 0 scripts
adachi-bot    | ✔ All packages installed (used 20ms(network 18ms), speed 0B/s, json 0(0B), tarball 0B)
adachi-bot    | 
adachi-bot    | > adachi-bot@2.2.10-bugfix1 start /bot
adachi-bot    | > ts-node -r tsconfig-paths/register app.ts --files
adachi-bot    | 
adachi-bot    | [2022-03-07T18:08:34.516] [MARK] [MacOS:1340398625] - ----------
adachi-bot    | [2022-03-07T18:08:34.520] [MARK] [MacOS:1340398625] - Package Version: oicq@1.21.3 (Released on 2021/12/08)
adachi-bot    | [2022-03-07T18:08:34.520] [MARK] [MacOS:1340398625] - View Changelogs：https://github.com/takayama-lily/oicq/releases
adachi-bot    | [2022-03-07T18:08:34.521] [MARK] [MacOS:1340398625] - ----------
adachi-bot    | [2022-03-07T18:08:34.541] [MARK] [MacOS:1340398625] - 正在探索可用服务器...
adachi-bot    | [2022-03-07T18:08:34.961] [INFO] [MacOS:1340398625] - 插件 @help 加载完成
adachi-bot    | [2022-03-07T18:08:35.472] [INFO] [MacOS:1340398625] - 插件 @management 加载完成
adachi-bot    | [2022-03-07T18:08:40.195] [INFO] [MacOS:1340398625] - 插件 genshin 加载完成
adachi-bot    | [2022-03-07T18:08:40.925] [INFO] [MacOS:1340398625] - 插件 genshin_draw_analysis 加载完成
adachi-bot    | [2022-03-07T18:08:41.257] [INFO] [MacOS:1340398625] - 插件 genshin_rating 加载完成
adachi-bot    | [2022-03-07T18:08:41.885] [INFO] [MacOS:1340398625] - 米游社签到定时已开启
adachi-bot    | [2022-03-07T18:08:42.031] [INFO] [MacOS:1340398625] - 插件 genshin_sign 加载完成
adachi-bot    | [2022-03-07T18:08:42.340] [INFO] [MacOS:1340398625] - 插件 music 加载完成
adachi-bot    | [2022-03-07T18:08:42.508] [INFO] [MacOS:1340398625] - 插件 tools 加载完成
adachi-bot    | [2022-03-07T18:08:42.511] [INFO] [MacOS:1340398625] - 事件监听启动成功
adachi-bot    | [2022-03-07T18:08:42.512] [INFO] [MacOS:1340398625] - Express 服务器已启动
adachi-bot    | [2022-03-07T18:08:42.512] [INFO] [MacOS:1340398625] - 抽卡记录服务已启动
adachi-bot    | [2022-03-07T18:08:42.513] [WARN] [MacOS:1340398625] - 探索服务器失败: timeout
adachi-bot    | [2022-03-07T18:08:42.513] [MARK] [MacOS:1340398625] - connecting to msfwifi.3g.qq.com:8080
adachi-bot    | [2022-03-07T18:08:42.570] [INFO] [MacOS:1340398625] - Redis 数据库已连接
adachi-bot    | [2022-03-07T18:08:42.654] [MARK] [MacOS:1340398625] - 120.232.67.190:8080 connected
adachi-bot    | [2022-03-07T18:08:42.682] [INFO] [MacOS:1340398625] - 浏览器启动成功
adachi-bot    | [2022-03-07T18:08:42.956] [INFO] [MacOS:1340398625] - 浏览器启动成功
adachi-bot    | [2022-03-07T18:08:43.089] [INFO] [MacOS:1340398625] - 用户 101291963 的实时便笺数据查询成功
adachi-bot    | [2022-03-07T18:08:43.116] [MARK] [MacOS:1340398625] - Welcome, 邚妃 ! 初始化资源...
adachi-bot    | [2022-03-07T18:08:43.336] [MARK] [MacOS:1340398625] - 加载了18个好友，3个群，0个陌生人。
adachi-bot    | [2022-03-07T18:08:43.474] [MARK] [MacOS:1340398625] - 初始化完毕，开始处理消息。
在发送#uid命令时报错，QQ提示图片渲染 异常，此外其他功能均正常，包括深渊正常查询

### 配置文件

```YAML
commands.yml  http://124.223.69.39:8888/down/8QBpw8PTiMKV
setting.yml  http://124.223.69.39:8888/down/TAUZBgJD3jev
cookies.yml  http://124.223.69.39:8888/down/RWKGSPNbU8WW

文件有点多，使用了宝塔面板的分享文件功能，主要就动了这三个文件，文件均隐去了QQ密码
```

### 错误报告

```Text
adachi-bot    | [2022-03-07T18:10:32.409] [INFO] [MacOS:1340398625] - recv from: [Group: 咕咕咕咕咕咕咕(790273600), Member: 我是温斯顿，璃月七星中的狂野猩(2435056792)] #uid[CQ:at,qq=2435056792,text=@我是温斯顿，璃月七星中的狂野猩]
adachi-bot    | [2022-03-07T18:10:32.470] [INFO] [MacOS:1340398625] - 用户 101291963 在一小时内进行过查询操作，将返回上次数据
adachi-bot    | [2022-03-07T18:10:33.497] [ERROR] [MacOS:1340398625] - SyntaxError: Unexpected token u in JSON at position 0
adachi-bot    |     at JSON.parse (<anonymous>)
adachi-bot    |     at /bot/src/plugins/genshin/routes/card-route.ts:10:22
adachi-bot    |     at step (/bot/src/plugins/genshin/routes/card-route.ts:33:23)
adachi-bot    |     at Object.next (/bot/src/plugins/genshin/routes/card-route.ts:14:53)
adachi-bot    |     at fulfilled (/bot/src/plugins/genshin/routes/card-route.ts:5:58)
adachi-bot    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
adachi-bot    | [2022-03-07T18:11:02.567] [ERROR] [MacOS:1340398625] - TimeoutError: Navigation timeout of 30000 ms exceeded
adachi-bot    |     at /bot/node_modules/puppeteer/src/common/LifecycleWatcher.ts:204:18
adachi-bot    | [2022-03-07T18:11:02.798] [INFO] [MacOS:1340398625] - send to: [Group: 790273600 / message_id: LxqeQE/k3CEAAbuSFyMm2WIl2jYB]
```

**Comment by SilveryStar** [comment]
这种情况可能是网络问题导致数据获取错误，可以考虑重启一下

**Comment by wickedll** [comment]
或者检查一下配置文件中的cookie格式是否有问题
