### ISSUE TITLE
查询数据缓存做null判断，一小时等待

### ISSUE THREAD

**Issue by Extrwave** [SilveryStar/Adachi-BOT#216]
### 系统版本

centos7

### Node.js 版本

14

### 应用版本

latest

### 启动方式

Docker

### 复述操作

当cookie.yaml里的cookie失效，或者用户未开启授权，使用了查询自己角色命令，比如`#我的角色 优菈`，就会返回不正确的结果
进行图片渲染时就会报错，报错信息贴在下面，配置好cookie后再次查询就需要等待一个小时（缓存过期），可不可以在写入缓存时候，对数据进行判断，如果不合法就不进行缓存，解决一小时等待问题

### 配置文件

```YAML
无关
```

### 错误报告

```Text
[21:13:31.748] [aPad:167490961] [INFO] - 用户 129431999 在一小时内进行过查询操作，将返回上次数据

[21:13:32.175] [aPad:167490961] [ERROR] - Error: Node has 0 height.
    at Object.assert (/bot/node_modules/puppeteer/src/common/assert.ts:23:21)
    at ElementHandle.screenshot (/bot/node_modules/puppeteer/src/common/JSHandle.ts:757:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by Extrwave** [comment]
补充：其他命令比如 查询自己主页，也会产生类似结果

**Comment by SilveryStar** [comment]
其实是有 check 的，`null` 是过不了的，具体哪里不合法也不清楚，你可以试着进 `redis-cli` 把这个字段删除再试一次或者把这个打印出来

**Comment by Extrwave** [comment]
Bot只对查询数据做了Redis缓存，能否对渲染好的图片做一个缓存呢？图片渲染才是最耗时的操作，我尝试对note标签写了个缓存样式，大佬看一下，有计划优化一下吗，类似`主页查询`，不用实时更新且渲染时间长的数据，优化一下会好很多
~~~
const imageList: string[] = [];
	for (let a of accounts) {
		const data: string = await a.services[NoteService.FixedField].toJSON();
		const uid: string = a.setting.uid;

		//获取redis中图片缓存
		const dbKeyImage: string = `silvery-star.note-temp-image-${uid}`;
		const tmpImage: string | null = await bot.redis.getString(dbKeyImage);
		if (tmpImage !== "" ) {
			bot.logger.info("redis缓存查询成功");
			imageList.push(tmpImage);
			continue;
		} else {
			bot.logger.info("redis没有此缓存，按原方式获取");
			//原code
			const dbKey: string = `silvery-star.note-temp-${uid}`;
			await bot.redis.setString(dbKey, data);
			const res: RenderResult = await renderer.asCqCode(
				"/note.html", { uid }
			);
			if (res.code === "ok") {
				imageList.push(res.data);
				//将图片缓存进redis，不用每次渲染,缓存5分钟
				await bot.redis.setString(dbKeyImage, res.data, 300);
			} else {
				bot.logger.error(res.error);
				imageList.push("图片渲染异常，请联系持有者进行反馈");
			}
		}
	}
~~~

**Comment by SilveryStar** [comment]
不太打算考虑，绝大多数情况下也不会再短时间内反复渲染同一张图片，缓存一小段时间的作用实在不大
