### ISSUE TITLE
windows环境下运行npm run win-start报错，没有生成配置文件

### ISSUE THREAD

**Issue by hydeng2022** [SilveryStar/Adachi-BOT#260]
$ npm run win-start

> adachi-bot@2.4.2-fix win-start C:\Users\Administrator\Desktop\Adachi-BOT
> ts-node -r tsconfig-paths/register app.ts --files

C:\Users\Administrator\Desktop\Adachi-BOT\node_modules\_typescript@4.7.4@typescript\lib\typescript.js:42537
        ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
                 ^
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (C:\Users\Administrator\Desktop\Adachi-BOT\node_modules\_typescript@4.7.4@typescript\lib\typescript.js:42537:18)
    at C:\Users\Administrator\Desktop\Adachi-BOT\node_modules\_ts-node@9.1.1@ts-node\src\index.ts:623:55
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (C:\Users\Administrator\Desktop\Adachi-BOT\node_modules\_ts-node@9.1.1@ts-node\src\index.ts:622:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (C:\Users\Administrator\Desktop\Adachi-BOT\node_modules\_typescript@4.7.4@typescript\lib\typescript.js:116674:163)
    at resolveTypeReferenceDirectiveNamesWorker (C:\Users\Administrator\Desktop\Adachi-BOT\node_modules\_typescript@4.7.4@typescript\lib\typescript.js:116974:26)
    at processTypeReferenceDirectives (C:\Users\Administrator\Desktop\Adachi-BOT\node_modules\_typescript@4.7.4@typescript\lib\typescript.js:118456:31)
    at findSourceFileWorker (C:\Users\Administrator\Desktop\Adachi-BOT\node_modules\_typescript@4.7.4@typescript\lib\typescript.js:118341:21)
    at findSourceFile (C:\Users\Administrator\Desktop\Adachi-BOT\node_modules\_typescript@4.7.4@typescript\lib\typescript.js:118196:26)
    at processImportedModules (C:\Users\Administrator\Desktop\Adachi-BOT\node_modules\_typescript@4.7.4@typescript\lib\typescript.js:118602:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adachi-bot@2.4.2-fix win-start: `ts-node -r tsconfig-paths/register app.ts --files`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adachi-bot@2.4.2-fix win-start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2022-06-22T03_21_06_832Z-debug.log

**Comment by MarryDream** [comment]
更新后删掉`node_modules`，执行`npm cache clean -f`，然后重新`npm i`试下还有没有问题
