### ISSUE TITLE
#imp 指令异常

### ISSUE THREAD

**Issue by SongZhiDan** [SilveryStar/Adachi-BOT#314]
### 系统版本

 Oct 5, 2022 代码版本（#313）

### Node.js 版本

v14.15.4

### 应用版本

2.7.7

### 复述操作

#imp

### 错误报告

```Text
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /root/Adachi-BOT/src/plugins/genshin/routes/artifact-route.ts:7:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Passerby-Fu** [comment]
你这个好像是json文件格式有错误 , 是启动后报错的吗?

**Comment by MarryDream** [comment]
> 你这个好像是json文件格式有错误 , 是启动后报错的吗?

这是个历史遗留问题，一直都忘记修了。没有执行过 `#art` 获取圣遗物的时候直接执行 `#imp` 会出现这个报错
