### ISSUE TITLE
使用docker-compose up -d构建时，第四步报错

### ISSUE THREAD

**Issue by Nigel-NI** [SilveryStar/Adachi-BOT#53]
删除了原有的adachi文件夹和有关的docker容器与images，重新拉取git，按步骤配置并启动bot时，前三步未见报错，第四步开始出现了问题，无法完成启动。
错误代码如下：

```js
Step 4/5 : RUN cnpm install
 ---> Running in 2dd54a359fc2
platform unsupported forever@3.0.4 › forever-monitor@3.0.3 › chokidar@2.1.8 › fsevents@^1.2.7 Package require os(darwin) not compatible with your platform(linux)
[fsevents@^1.2.7] optional install error: Package require os(darwin) not compatible with your platform(linux)
✔ Installed 23 packages
✔ Linked 473 latest versions
[1/1] scripts.install puppeteer@^10.0.0 run "node install.js", root: "/bot/node_modules/_puppeteer@10.2.0@puppeteer"
ERROR: Failed to set up Chromium r901912! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: end of central directory record signature not found
    at /bot/node_modules/_yauzl@2.10.0@yauzl/index.js:187:14
    at /bot/node_modules/_yauzl@2.10.0@yauzl/index.js:631:5
    at /bot/node_modules/_fd-slicer@1.1.0@fd-slicer/index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
[npminstall:runscript:error] puppeteer@^10.0.0 scripts.install run "node install.js" error: Error [RunScriptError]: Run "sh -c node install.js" error, exit code 1
    at ChildProcess.<anonymous> (/usr/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  stdio: [Object],
  exitcode: 1
}
✖ Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node install.js" error, exit code 1
RunScriptError: Run "sh -c node install.js" error, exit code 1
    at ChildProcess.<anonymous> (/usr/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npminstall version: 3.28.0
npminstall args: /usr/bin/node /usr/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.nlark.com
ERROR: Service 'bot' failed to build: The command '/bin/sh -c cnpm install' returned a non-zero code: 1
```

**Comment by SilveryStar** [comment]
`chromium` 下载失败，可以在 `Dockerfile` 里 `RUN cnpm install` 前面加一行`RUN npm config set puppeteer_download_host=https://npm.taobao.org/mirrors` 试试

**Comment by Nigel-NI** [comment]
这次docker倒是启动了，但是bot仍无法运行，docker输出日志如下：
```js
/bot/node_modules/_yaml@1.10.2@yaml/dist/resolveSeq-d03cb037.js:1568
      errors.push(new PlainValue.YAMLReferenceError(node, msg));
                  ^
YAMLReferenceError: Aliased anchor not found: 
    at resolveNodeValue (/bot/node_modules/_yaml@1.10.2@yaml/dist/resolveSeq-d03cb037.js:1568:19)
    at resolveNode (/bot/node_modules/_yaml@1.10.2@yaml/dist/resolveSeq-d03cb037.js:1629:15)
    at resolveBlockMapItems (/bot/node_modules/_yaml@1.10.2@yaml/dist/resolveSeq-d03cb037.js:1823:38)
    at Object.resolveMap [as resolve] (/bot/node_modules/_yaml@1.10.2@yaml/dist/resolveSeq-d03cb037.js:1658:79)
    at resolveByTagName (/bot/node_modules/_yaml@1.10.2@yaml/dist/resolveSeq-d03cb037.js:1430:25)
    at resolveTag (/bot/node_modules/_yaml@1.10.2@yaml/dist/resolveSeq-d03cb037.js:1460:17)
    at resolveNodeValue (/bot/node_modules/_yaml@1.10.2@yaml/dist/resolveSeq-d03cb037.js:1581:23)
    at Object.resolveNode (/bot/node_modules/_yaml@1.10.2@yaml/dist/resolveSeq-d03cb037.js:1629:15)
    at parseContents (/bot/node_modules/_yaml@1.10.2@yaml/dist/Document-9b4560a1.js:357:30)
    at Document.parse (/bot/node_modules/_yaml@1.10.2@yaml/dist/Document-9b4560a1.js:615:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adachi-bot@2.0.5 start: `ts-node app.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the adachi-bot@2.0.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-14T15_07_23_315Z-debug.log
```

以下是重新指定镜像服务器后执行docker-compose up -d时的部分日志：
```
Step 4/6 : RUN npm config set puppeteer_download_host=https://npm.taobao.org/mirrors
 ---> Running in d8e6377ff2d6
Removing intermediate container d8e6377ff2d6
 ---> bc000631289d
Step 5/6 : RUN cnpm install
 ---> Running in 0d22546a5fc6
platform unsupported forever@3.0.4 › forever-monitor@3.0.3 › chokidar@2.1.8 › fsevents@^1.2.7 Package require os(darwin) not compatible with your platform(linux)
[fsevents@^1.2.7] optional install error: Package require os(darwin) not compatible with your platform(linux)
✔ Installed 23 packages
✔ Linked 473 latest versions
[1/1] scripts.install puppeteer@^10.0.0 run "node install.js", root: "/bot/node_modules/_puppeteer@10.2.0@puppeteer"

Chromium (901912) downloaded to /bot/node_modules/_puppeteer@10.2.0@puppeteer/.local-chromium/linux-901912
[1/1] scripts.install puppeteer@^10.0.0 finished in 17s
✔ Run 1 scripts
peerDependencies WARNING puppeteer@10.2.0 › ws@7.4.6 requires a peer of bufferutil@^4.0.1 but none was installed
peerDependencies WARNING puppeteer@10.2.0 › ws@7.4.6 requires a peer of utf-8-validate@^5.0.2 but none was installed
anti semver @types/node-schedule@1.3.2 › @types/node@* delcares @types/node@*(resolved as 16.6.1) but using ancestor(root package.json)'s dependency @types/node@^15.0.2(resolved as 15.14.7)
anti semver @types/request@2.48.7 › @types/node@* delcares @types/node@*(resolved as 16.6.1) but using ancestor(root package.json)'s dependency @types/node@^15.0.2(resolved as 15.14.7)
anti semver @types/express@4.17.13 › @types/express-serve-static-core@4.17.24 › @types/node@* delcares @types/node@*(resolved as 16.6.1) but using ancestor(root package.json)'s dependency @types/node@^15.0.2(resolved as 15.14.7)
anti semver @types/express@4.17.13 › @types/body-parser@1.19.1 › @types/node@* delcares @types/node@*(resolved as 16.6.1) but using ancestor(root package.json)'s dependency @types/node@^15.0.2(resolved as 15.14.7)
anti semver @types/express@4.17.13 › @types/serve-static@1.13.10 › @types/node@* delcares @types/node@*(resolved as 16.6.1) but using ancestor(root package.json)'s dependency @types/node@^15.0.2(resolved as 15.14.7)
anti semver @types/express@4.17.13 › @types/body-parser@1.19.1 › @types/connect@3.4.35 › @types/node@* delcares @types/node@*(resolved as 16.6.1) but using ancestor(root package.json)'s dependency @types/node@^15.0.2(resolved as 15.14.7)
deprecate forever@3.0.4 › forever-monitor@3.0.3 › chokidar@^2.1.8 Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
deprecate request@^2.88.2 request has been deprecated, see https://github.com/request/request/issues/3142
anti semver puppeteer@10.2.0 › extract-zip@2.0.1 › @types/yauzl@2.9.2 › @types/node@* delcares @types/node@*(resolved as 16.6.1) but using ancestor(root package.json)'s dependency @types/node@^15.0.2(resolved as 15.14.7)
deprecate request@2.88.2 › har-validator@~5.1.3 this library is no longer supported
deprecate forever@3.0.4 › forever-monitor@3.0.3 › chokidar@2.1.8 › fsevents@^1.2.7 fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
deprecate forever@3.0.4 › forever-monitor@3.0.3 › chokidar@2.1.8 › braces@2.3.2 › snapdragon@0.8.2 › source-map-resolve@0.5.3 › urix@^0.1.0 Please see https://github.com/lydell/urix#deprecated
deprecate forever@3.0.4 › forever-monitor@3.0.3 › chokidar@2.1.8 › braces@2.3.2 › snapdragon@0.8.2 › source-map-resolve@0.5.3 › resolve-url@^0.2.1 https://github.com/lydell/resolve-url#deprecated
Recently updated (since 2021-08-07): 11 packages (detail see file /bot/node_modules/.recently_updates.txt)
  Today:
    → oicq@^1.18.0(1.19.1) (07:15:14)
✔ All packages installed (569 packages installed from npm registry, used 47s(network 30s), speed 800.9kB/s, json 496(1.8MB), tarball 21.5MB)
Removing intermediate container 0d22546a5fc6
 ---> f23b753fd522
Step 6/6 : CMD [ "npm", "start" ]
 ---> Running in ca51ed8b9aef
Removing intermediate container ca51ed8b9aef
 ---> 0b00211ab017
Successfully built 0b00211ab017
Successfully tagged adachi-bot_bot:latest
```

**Comment by SilveryStar** [comment]
你是不是重新拉取忘记配置 config 了

**Comment by Nigel-NI** [comment]
在删除adachi-bot文件夹之前，我备份了config文件夹，重新拉取后对后者进行还原，无关文件全部删除，只留下了cookies,  setting和commands（删掉所有内容，保留一个空文件）三个yml，且这三个文件里面的内容都是保持原样的（除了settings里面的header由""改成了*）

**Comment by SilveryStar** [comment]
那大概是因为你的 `*` 没有加双引号表示字符串，这个符号在 yaml 里具有语义，必须加引号作为纯量表示

**Comment by Nigel-NI** [comment]
确实，加了单引号之后就正常了。感谢开发大大，辛苦啦
