### ISSUE TITLE
使用docker-compose up -d重新拉取后bot启动失败，提示"Unable to compile TypeScript"

### ISSUE THREAD

**Issue by Nigel-NI** [SilveryStar/Adachi-BOT#57]
### 环境
- 系统：Debian 10
- node 版本：v14.17.3
- bot 版本：2.0.6

### 操作复述
删除bot的docker容器与镜像后使用docker-compose up -d重新拉取，查询日志发现启动失败，

### 配置文件
略。setting.yml文件中命令头字母已用“”处理，cookies.yml格式符合“- _MHYUID”。重新拉取代码前各项功能一切正常，拉取代码过程中未对config文件夹内容进行改动。

### 错误报告
```
/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/modules/message.ts(41,14): error TS2339: Property 'message_type' does not exist on type 'CommonMessageEventData'.
src/modules/message.ts(45,14): error TS2339: Property 'message_type' does not exist on type 'CommonMessageEventData'.

    at createTSError (/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:513:12)
    at reportTSError (/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:517:19)
    at getOutput (/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:752:36)
    at Object.compile (/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:968:32)
    at Module.m._compile (/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adachi-bot@2.0.6 start: `ts-node app.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the adachi-bot@2.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-01T15_39_36_200Z-debug.log
```

**Comment by SilveryStar** [comment]
fix，可尝试重新拉取

**Comment by Nigel-NI** [comment]
重新拉取后仍旧报错，输入指令后bot无响应。错误日志如下：
```
(node:19) UnhandledPromiseRejectionWarning: TSError: ⨯ Unable to compile TypeScript:
src/plugins/genshin/module/artifact.ts(237,4): error TS2322: Type 'unknown' is not assignable to type 'string'.

    at createTSError (/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:513:12)
    at reportTSError (/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:517:19)
    at getOutput (/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:752:36)
    at Object.compile (/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:968:32)
    at Module.m._compile (/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/bot/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SilveryStar** [comment]
新 commit 我部署了一遍应该没问题了，不清楚为什么 docker 环境检查了这个……

**Comment by Nigel-NI** [comment]
上面的问题解决了，不过又出现了新的报错，输入指令还是无响应（日志如下）……
```
[2021-09-02T02:38:45.363] [INFO] [Android:***] - Express 服务器已启动
(node:19) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_launcher' of undefined
    at launch (/bot/node_modules/_puppeteer@10.2.0@puppeteer/src/node/Puppeteer.ts:155:17)
    at /bot/src/plugins/genshin/utils/render.ts:7:24
    at step (/bot/src/plugins/genshin/utils/render.ts:33:23)
    at Object.next (/bot/src/plugins/genshin/utils/render.ts:14:53)
    at /bot/src/plugins/genshin/utils/render.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/src/plugins/genshin/utils/render.ts:4:12)
    at createBrowser (/bot/src/plugins/genshin/utils/render.ts:44:12)
    at /bot/src/plugins/genshin/init.ts:151:21
    at step (/bot/src/plugins/genshin/init.ts:44:23)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SilveryStar** [comment]
为什么用 docker 还能有部署差异啊/捂脸，你重新 clone 一个？这种错误我属实没头绪

**Comment by SilveryStar** [comment]
现在（大概）好了
