### ISSUE TITLE
求签没有返回消息

### ISSUE THREAD

**Issue by Lenhee** [SilveryStar/Adachi-BOT#62]
错误：
 Error: empty message
    at Builder.buildAndSend (E:\Adachi-BOT\node_modules\oicq\lib\message\builder.js:905:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Client._useProtocol (E:\Adachi-BOT\node_modules\oicq\lib\client.js:179:25)
    
建议：每天多次求签可以返回相同内容，而非第二次及之后提示今日求过了

**Comment by SilveryStar** [comment]
返回相同内容已经更新了，你的给出的错误报告我无法定位错误原因
