### ISSUE TITLE
机器人无回复，手动启动时显示端口已被占用

### ISSUE THREAD

**Issue by Mark9804** [SilveryStar/Adachi-BOT#65]
### 环境
- 搭建方式：docker，后尝试forever
- 系统：macOS 11.6 (20G165)
- node 版本：16.10.0
- bot 版本：2.0.7

### 操作复述

1. 在宿主机内运行`npm run login`，确认QQ已登录；
2. 运行`docker-compose up -d`；docker dashboard确认容器正在运行
3. 测试机器人，测试命令为`@机器人昵称 info 刻晴`
4. 检查宿主机log，确认收到消息：`[2021-09-24T20:00:55.645] [INFO] [Android:***] - recv from: [Group: ***(******), Member:***(********)] [CQ:at,qq=***,text=@阿晴二号机]  info 刻晴`。未收到机器人回复
5. 手动运行机器人：`npm start serve`
6. 收到错误消息：`Error: listen EADDRINUSE: address already in use :::58612`
7. 查看端口占用信息
```
$ lsof -i:58612
COMMAND   PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node     12722     ****   28u  IPv6       0x1d6f5ea135bec743      0t0  TCP *:58612 (LISTEN)
```

### 配置文件

```
# config/cookies.yml
cookies:
  - _MHYUUID=****; mi18nLang=zh-cn; login_uid=****; login_ticket=****; account_id=****; cookie_token=****; ltoken=****; ltuid=****

```
```
# config/setting.yml
qrcode: false       # 是否启用扫码登录
                    # 每次登录都需验证,Docker启动禁用,默认不启用
number: ***    # QQ 账号
password: "****"        # QQ 密码
master: ****    # BOT 持有者账号
header: ""          # 命令起始符(可为空串"")
platform: 4         # 登录平台
                    # 1.安卓手机(默认) 2.aPad 3.安卓手表 4.MacOS 5.iPad
atUser: false        # 是否启用回复时 at 用户,默认关闭
dbPort: 56379       # 数据库端口
                    # 修改该选项需同时修改 redis.conf -> port
intervalTime: 1500  # 指令操作冷却时间,单位毫秒,默认 1500ms
```
### 错误报告
```
$ npm start serve

> adachi-bot@2.0.7 start
> ts-node app.ts "serve"

====================================================================
                _            _     _        ____   ____ _______
       /\      | |          | |   (_)      |  _ \ / __ \__   __|
      /  \   __| | __ _  ___| |__  _ ______| |_) | |  | | | |
     / /\ \ / _` |/ _` |/ __| '_ \| |______|  _ <| |  | | | |
    / ____ \ (_| | (_| | (__| | | | |      | |_) | |__| | | |
   /_/    \_\__,_|\__,_|\___|_| |_|_|      |____/ \____/  |_|

====================================================================
[2021-09-24T19:50:46.249] [MARK] [MacOS:*********] - ----------
[2021-09-24T19:50:46.251] [MARK] [MacOS:*********] - Package Version: oicq@1.20.2 (Released on 2021/9/12)
[2021-09-24T19:50:46.251] [MARK] [MacOS:*********] - View Changelogs：https://github.com/takayama-lily/oicq/releases
[2021-09-24T19:50:46.251] [MARK] [MacOS:*********] - ----------
[2021-09-24T19:50:46.260] [MARK] [MacOS:*********] - 正在探索可用服务器...
[2021-09-24T19:50:47.054] [INFO] [MacOS:*********] - 插件 @auth 已成功加载
[2021-09-24T19:50:47.610] [INFO] [MacOS:*********] - 插件 @help 已成功加载
[2021-09-24T19:50:50.420] [INFO] [MacOS:*********] - Redis 数据库已连接
[2021-09-24T19:50:50.885] [DEBUG] [MacOS:*********] - {
  '203.205.255.221': 8080,
  '203.205.232.56': 8080,
  '203.205.255.224': 8080
}
[2021-09-24T19:50:50.886] [MARK] [MacOS:*********] - connecting to 203.205.255.221:8080
[2021-09-24T19:50:50.955] [MARK] [MacOS:*********] - 203.205.255.221:8080 connected
Error: listen EADDRINUSE: address already in use :::58612
    at Server.setupListenHandle [as _listen2] (node:net:1319:16)
    at listenInCluster (node:net:1367:12)
    at Server.listen (node:net:1454:7)
    at Function.listen (/Users/****/Documents/GitHub.nosync/Adachi-BOT/node_modules/express/lib/application.js:618:24)
    at Object.createServer (/Users/****/Documents/GitHub.nosync/Adachi-BOT/src/plugins/genshin/server.ts:22:6)
    at /Users/****/Documents/GitHub.nosync/Adachi-BOT/src/plugins/genshin/init.ts:162:2
    at step (/Users/****/Documents/GitHub.nosync/Adachi-BOT/src/plugins/genshin/init.ts:44:23)
    at Object.next (/Users/****/Documents/GitHub.nosync/Adachi-BOT/src/plugins/genshin/init.ts:25:53)
    at fulfilled (/Users/****/Documents/GitHub.nosync/Adachi-BOT/src/plugins/genshin/init.ts:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by SilveryStar** [comment]
关于操作 3，该 bot 不需要通过 @ bot 账号来使用，@ 会导致正则无法匹配而不进行回复

**Comment by SilveryStar** [comment]
端口占用可能是没 stop docker 进程？如果确定已经关闭不妨先修改 `genshin.yml` 里面的 serverPort，这个问题没出现过，如果是这种情况我再思考一下

**Comment by Mark9804** [comment]
尝试成功了，有点玄学

1. 启动docker image后，在docker环境下`yum install lsof; lsof -i:58612`发现无占用进程
2. `npm start serve`，报错，是macOS上特有的问题：
```
(node:104) UnhandledPromiseRejectionWarning: Error: Cannot find module '/bot/src/plugins/.DS_Store/init'
Require stack:
- /bot/src/modules/plugin.ts
- /bot/src/bot.ts
- /bot/app.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/src/modules/plugin.ts:24:20)
    at step (/bot/src/modules/plugin.ts:33:23)
    at Object.next (/bot/src/modules/plugin.ts:14:53)
    at /bot/src/modules/plugin.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/src/modules/plugin.ts:4:12)
(node:104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
报错的原因是macOS会自动在每个目录写入`.DS_Store`桌面布局文件，node在遍历`plugin`文件夹时将这个文件当作插件目录处理导致无法启动，因此`rm -r`移除该文件。
3. 再次尝试启动。报错无Chromium，运行`npm install`安装。
4. 再次尝试启动，正常启动。
