### ISSUE TITLE
src/plugins/@auth/init.ts(38,3): error TS2322: Type '"switch"' is not assignable to type '"order" | "question"'.

### ISSUE THREAD

**Issue by Flyky** [SilveryStar/Adachi-BOT#72]
### 环境
- 系统：CentOS
- node 版本：v14.17.6
- bot 版本：adachi-bot@2.0.6

### 操作复述
clone 后按照手册步骤配置，之后 `docker-compose up` 启动bot
bot虽然正常运行，可接收消息，但并没有收到bot回复，后台发现报错

### 配置文件
qrcode: false       # 是否启用扫码登录
                    # 每次登录都需验证,Docker启动禁用,默认不启用
number: xxxxxx    # QQ 账号
password: "xxxxxxxxxaxxx"        # QQ 密码
master: xxxxxx    # BOT 持有者账号
header: "#"          # 命令起始符(可为空串"")
platform: 2         # 登录平台
                    # 1.安卓手机(默认) 2.aPad 3.安卓手表 4.MacOS 5.iPad
atUser: true        # 是否启用回复时 at 用户,默认关闭
dbPort: 56379       # 数据库端口
                    # 修改该选项需同时修改 redis.conf -> port
intervalTime: 1500  # 指令操作冷却时间,单位毫秒,默认 1500ms

### 错误报告
adachi-bot | (node:17) UnhandledPromiseRejectionWarning: TSError: ⨯ Unable to compile TypeScript:
adachi-bot | src/plugins/@auth/init.ts(38,3): error TS2322: Type '"switch"' is not assignable to type '"order" | "question"'.
adachi-bot |
adachi-bot |     at createTSError (/bot/node_modules/ts-node/src/index.ts:513:12)
adachi-bot |     at reportTSError (/bot/node_modules/ts-node/src/index.ts:517:19)
adachi-bot |     at getOutput (/bot/node_modules/ts-node/src/index.ts:752:36)
adachi-bot |     at Object.compile (/bot/node_modules/ts-node/src/index.ts:968:32)
adachi-bot |     at Module.m._compile (/bot/node_modules/ts-node/src/index.ts:1056:42)
adachi-bot |     at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
adachi-bot |     at Object.require.extensions.<computed> [as .ts] (/bot/node_modules/ts-node/src/index.ts:1059:12)
adachi-bot |     at Module.load (internal/modules/cjs/loader.js:863:32)
adachi-bot |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
adachi-bot |     at Module.require (internal/modules/cjs/loader.js:887:19)
adachi-bot | (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
adachi-bot | (node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Flyky** [comment]
没事了，镜像要更新一下
