### ISSUE TITLE
启动报错：listen EACCES: permission denied 0.0.0.0:58612

### ISSUE THREAD

**Issue by AzusaYukina** [SilveryStar/Adachi-BOT#83]
### 环境
- 系统：Windows 10 Pro (Build 19043.1288)
- node 版本：v14.18.1
- bot 版本：2.1.6

### 操作复述
尝试本地调试时使用全新设置并且已经采用 Readme 中操作启动了 redis 数据库，启动 bot 报错。

### 配置文件
Readme 中配置文件，仅修改了 QQ 账号密码。

### 错误报告

```
Error: listen EACCES: permission denied 0.0.0.0:58612
    at Server.setupListenHandle [as _listen2] (net.js:1314:21)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Function.listen (D:\GitHub\Adachi-BOT\node_modules\express\lib\application.js:618:24)
    at Object.createServer (D:\GitHub\Adachi-BOT\src\plugins\genshin\server.ts:17:6)
    at D:\GitHub\Adachi-BOT\src\plugins\genshin\init.ts:66:2
    at step (D:\GitHub\Adachi-BOT\src\plugins\genshin\init.ts:52:23)
    at Object.next (D:\GitHub\Adachi-BOT\src\plugins\genshin\init.ts:33:53)
    at D:\GitHub\Adachi-BOT\src\plugins\genshin\init.ts:27:71
    at new Promise (<anonymous>)
```

**Comment by AzusaYukina** [comment]
一个值得注意的地方是，重启计算机之后虽然可以启动了，暂时不清楚这种情况在什么时候会出现。
推测和多开有关，但是并没有证据，

**Comment by SilveryStar** [comment]
多开的话是肯定不行的，如果是之前开的关了之后再开新的报错可能是没完全杀掉，需要手动，我这边 Windows 也出现过这种情况

**Comment by AzusaYukina** [comment]
目前确定是多开问题，所以之后会针对多开优化一下吗，群多了确实可能有这个必要。

**Comment by SilveryStar** [comment]
你要多开的话，另外 clone 一个改 genshin.yml 里的 serverPort 就行了

**Comment by AzusaYukina** [comment]
我试试看
