### ISSUE TITLE
指令报错：使用指令alm后报错 (node:4572) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by VsentCN** [SilveryStar/Adachi-BOT#85]
### 环境
- 系统：	
Windows Server 2019 DataCenter 64bitCN
- node 版本：13.13.0
- bot 版本：2.1.13

### 操作复述

输入指令alm后，机器人不会回复，后台报错，未经行其他操作
### 配置文件

未修改过配置文件
### 错误报告
(node:4572) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at AlmanacClass.getUnits (C:\bot\src\plugins\genshin\module\almanac.ts:57:2)
    at AlmanacClass.getUnits (C:\bot\src\plugins\genshin\module\almanac.ts:69:10)
    at AlmanacClass.getUnits (C:\bot\src\plugins\genshin\module\almanac.ts:69:10)
    at AlmanacClass.getUnits (C:\bot\src\plugins\genshin\module\almanac.ts:69:10)
    at AlmanacClass.getUnits (C:\bot\src\plugins\genshin\module\almanac.ts:69:10)
    at AlmanacClass.getUnits (C:\bot\src\plugins\genshin\module\almanac.ts:69:10)
    at AlmanacClass.getUnits (C:\bot\src\plugins\genshin\module\almanac.ts:69:10)
    at AlmanacClass.getUnits (C:\bot\src\plugins\genshin\module\almanac.ts:69:10)
    at AlmanacClass.getUnits (C:\bot\src\plugins\genshin\module\almanac.ts:69:10)
    at AlmanacClass.getUnits (C:\bot\src\plugins\genshin\module\almanac.ts:69:10)
(node:4572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by SilveryStar** [comment]
下个版本修，得等一段时间

**Comment by SilveryStar** [comment]
很神奇，这个功能貌似莫名其妙的好了，我今天刚想修发现服务器部署的 v2.2.0-beta2 这个功能能正常用了

**Comment by SilveryStar** [comment]
要不你也试试？没问题的话我就把issue关了XD

**Comment by VsentCN** [comment]
> 要不你也试试？没问题的话我就把issue关了XD

事实上我提出问题之后过了段时间到现在，他也正常了，似乎只出现了那一天。

**Comment by SilveryStar** [comment]
我倒是也复现过这种情况，本机正常服务器报错，主要还是这边代码可莉特调那压缩后的源码人脑翻译回来的，可能有点问题，但我一时半会儿看不出来（趴

**Comment by VsentCN** [comment]
> 我倒是也复现过这种情况，本机正常服务器报错，主要还是这边代码可莉特调那压缩后的源码人脑翻译回来的，可能有点问题，但我一时半会儿看不出来（趴
不排除是可莉特调网站那边出了问题

**Comment by SilveryStar** [comment]
那……我就先关了吧，要是再出问题麻烦你reopen一下（
