### ISSUE TITLE
输入指令slip后，有几率出现undefined

### ISSUE THREAD

**Issue by VsentCN** [SilveryStar/Adachi-BOT#87]
### 环境
- 系统：	
Windows Server 2019 DataCenter 64bitCN
- node 版本：13.13.0
- bot 版本：2.1.13

### 操作复述

输入指令slip后，有几率出现undefined
### 配置文件

未修改过配置文件
### 错误报告
[2021-11-06T10:22:39.979] [ERROR] [Watch:2799622239] - Invoke failed, because -> empty message
[2021-11-06T10:22:39.979] [DEBUG] [Watch:2799622239] - Error: empty message
    at Builder.buildAndSend (C:\bot\node_modules\oicq\lib\message\builder.js:850:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Client._useProtocol (C:\bot\node_modules\oicq\lib\client.js:210:25)

**Comment by SilveryStar** [comment]
信息太少了，实在没法定位错误发生的原因，我就多加了两个判断，然后测试跑了1k次也没出问题，就当修好了（
